import Head from "next/head";
import Link from "next/link";

const Home = () => {
  const style = {
    display: "block",
    cursor: "pointer",
    fontSize: "34px",
    color: "black",
    textDecoration: "none",
  };
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/ssg/post">
        <a style={style}>Static Site Generation</a>
      </Link>
      <br />
      <Link href="/ssg/todo">
        <a style={style}>Server Side Rendering</a>
      </Link>
    </div>
  );
};

export default Home;
