import Head from "next/head";
import Link from "next/link";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/ssg/post">
        <h1 style={{ cursor: "pointer" }}>Static Site Generation</h1>
      </Link>
      <br />
      <Link href="/ssg/todo">
        <h1 style={{ cursor: "pointer" }}>Server Side Rendering</h1>
      </Link>
    </div>
  );
};

export default Home;
